# Generated by Django 4.2.2 on 2023-06-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Vendido',
            fields=[
                ('sku_vendido', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_vendido', models.CharField(max_length=50)),
                ('precio_vendido', models.IntegerField()),
                ('stock_vendido', models.IntegerField()),
                ('fecha_vendido', models.DateField(auto_now_add=True)),
                ('descripcion_vendido', models.CharField(max_length=120)),
                ('imagenUrl_vendido', models.ImageField(upload_to='imagenesProducto')),
                ('categoriaId_vendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dplants.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('imagenUrl', models.ImageField(upload_to='imagenesProducto')),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dplants.categoria')),
            ],
        ),
    ]
